theme: butterfly
menu:
  首页: / || fas fa-home
  文章||fas fa-archive:
    归档: /archives/ || fas fa-archive
    标签: /tags/ || fas fa-tags
    分类: /categories/ || fas fa-folder-open
  娱乐||fas fa-list:
    相册: /gallery/ || fas fa-images
  Link: /link/ || fas fa-link
  About: /about/ || fas fa-heart
nav:
  logo: #image
  display_title: true
  fixed: false # fixed navigation bar
highlight_copy: true
highlight_theme: light
highlight_shrink: true #代码框不展开，需点击 '>' 打开
code_word_wrap: true
highlight_height_limit: false # unit: px
social:
  fab fa-github: https://github.com/xxxxx || Github
  fas fa-envelope: mailto:xxxxxx@gmail.com || Email
index_post_content:
  method: 3
  length: 500 # if you set method to 2 or 3, the length need to config
disable_top_img: true